project_id = "miisgijrhzrjxojogtdk"

[functions.create-song-folder]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.upload-to-drive]
verify_jwt = true

[functions.delete-from-drive]
verify_jwt = true

[functions.stream-drive-audio]
verify_jwt = false

[functions.upload-banner-image]
verify_jwt = true

[functions.rename-drive-folder]
verify_jwt = false